@startuml
autonumber

control ":ControllerActor" as controller
control ":SimulationManagerActor" as simulationManager
control ":CelestialBodyActor" as celestialBody
control ":EventRecorderActor" as eventRecorder

activate controller
activate simulationManager
activate celestialBody
activate eventRecorder

controller --> simulationManager: StartSimulation()

loop
    simulationManager --> simulationManager: IterationStep()
    simulationManager --> celestialBody: UpdateCelestialBodyType(self)
    celestialBody --> simulationManager: CelestialBodyState(celestialBody, celestialBodyType)
    simulationManager --> simulationManager: IterationStep()
    simulationManager --> celestialBody: MoveToNextPosition(tmpState, self)
    celestialBody --> simulationManager: CelestialBodyState(celestialBody, celestialBodyType)
    simulationManager --> simulationManager: IterationStep()
    simulationManager --> celestialBody: SolveCollisions(tmpState, self)
    celestialBody --> eventRecorder: RecordCollision(celestialBody1, celestialBody2)
    celestialBody --> simulationManager: CelestialBodyState(celestialBody, celestialBodyType)
    simulationManager --> simulationManager: IterationStep()
end

controller --> simulationManager: StopSimulation()

@enduml