@startuml
'https://plantuml.com/class-diagram

package galaxy_sim.view{
    class View << trait >>
    class SwingGUI
}

package galaxy_sim.actors{
    class ViewActor << object >>
}

View --> SwingGUI : use
SwingGUI --> View : use
View --> ViewActor : use
ViewActor --> View : use

@enduml