name: GitHub Release

on:
  push:
    tags:
      - '*'

jobs:
  call-code-coverage-workflow:
    uses: ./.github/workflows/code-coverage.yml

  build:
    needs: call-code-coverage-workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Create Artifact
        run: sbt assembly

      - uses: actions/upload-artifact@v3.1.0
        with:
          name: release
          path: target/scala-3.2.0/galaxy-sim.jar

  tagged-release:
    name: Create release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: release
          path: target/scala-3.2.0/galaxy-sim.jar
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: target/scala-3.2.0/galaxy-sim.jar